import express from 'express'
import cors from 'cors'
import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { RESOURCES, readJson, updateJson } from './lib/store.js'
import { INTERESTS, validateEnquiry, validateEmail } from './lib/validate.js'

const PORT = process.env.PORT || 3001
const app = express()
app.disable('x-powered-by')
app.use(cors())
app.use(express.json({ limit: '20kb' }))

// ---- tiny in-memory rate limiter for write endpoints -----------------------
const hits = new Map()
const rateLimit = (max, windowMs) => (req, res, next) => {
  const key = `${req.ip}:${req.path}`
  const now = Date.now()
  const recent = (hits.get(key) ?? []).filter((t) => now - t < windowMs)
  if (recent.length >= max) return res.status(429).json({ error: 'Too many requests. Please try again shortly.' })
  recent.push(now)
  hits.set(key, recent)
  next()
}

// ---- meta ------------------------------------------------------------------
app.get('/api', (_req, res) => {
  res.json({
    name: 'Alpine Ascents API',
    resources: RESOURCES.map((r) => `/api/${r}`),
    endpoints: ['GET /api/visitors', 'POST /api/visitors/hit', 'POST /api/enquiry', 'POST /api/newsletter', 'GET /api/enquiry/interests'],
  })
})
app.get('/api/health', (_req, res) => res.json({ ok: true, time: new Date().toISOString() }))

// ---- visitor counter -------------------------------------------------------
// A session id (generated by the browser, once per session) makes the hit idempotent.
const seenSessions = new Set()

app.get('/api/visitors', async (_req, res, next) => {
  try {
    const { count } = await readJson('visitors', { count: 0 })
    res.json({ count })
  } catch (e) { next(e) }
})

app.post('/api/visitors/hit', rateLimit(30, 60_000), async (req, res, next) => {
  try {
    const sid = typeof req.body?.sessionId === 'string' ? req.body.sessionId.slice(0, 64) : null
    if (sid && seenSessions.has(sid)) {
      const { count } = await readJson('visitors', { count: 0 })
      return res.json({ count, counted: false })
    }
    if (sid) seenSessions.add(sid)
    const next_ = await updateJson('visitors', { count: 0 }, (v) => ({
      ...v,
      count: (v.count ?? 0) + 1,
      lastVisit: new Date().toISOString(),
    }))
    res.json({ count: next_.count, counted: true })
  } catch (e) { next(e) }
})

// ---- enquiries & newsletter -------------------------------------------------
app.get('/api/enquiry/interests', (_req, res) => res.json(INTERESTS))

app.post('/api/enquiry', rateLimit(8, 60_000), async (req, res, next) => {
  try {
    // Honeypot: bots fill hidden "website" field. Pretend success, store nothing.
    if (req.body?.website) return res.status(201).json({ ok: true, id: 'ignored' })
    const { errors, value } = validateEnquiry(req.body)
    if (Object.keys(errors).length) return res.status(422).json({ error: 'Please correct the highlighted fields.', errors })
    const entry = { id: crypto.randomUUID(), ...value, createdAt: new Date().toISOString() }
    await updateJson('enquiries', [], (list) => [...list, entry])
    res.status(201).json({ ok: true, id: entry.id, message: 'Thank you. A guide will reply within one working day.' })
  } catch (e) { next(e) }
})

app.post('/api/newsletter', rateLimit(8, 60_000), async (req, res, next) => {
  try {
    const email = validateEmail(req.body?.email)
    if (!email) return res.status(422).json({ error: 'Please enter a valid email address.' })
    await updateJson('newsletter', [], (list) =>
      list.some((s) => s.email === email) ? list : [...list, { email, createdAt: new Date().toISOString() }],
    )
    res.status(201).json({ ok: true, message: 'You are on the list. Welcome to the expedition.' })
  } catch (e) { next(e) }
})

// ---- content collections: GET /api/<resource> -------------------------------
app.get('/api/:resource', async (req, res, next) => {
  const { resource } = req.params
  if (!RESOURCES.includes(resource)) return next()
  try {
    res.set('Cache-Control', 'public, max-age=60')
    res.json(await readJson(resource))
  } catch (e) { next(e) }
})

// ---- optionally serve the built client (npm start) ------------------------
const clientDir = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'client')
if (fs.existsSync(path.join(clientDir, 'index.html'))) {
  app.use(express.static(clientDir, { maxAge: '1h', index: 'index.html' }))
}

// ---- 404 + error handling ---------------------------------------------------
app.use('/api', (_req, res) => res.status(404).json({ error: 'Not found' }))
app.use((err, _req, res, _next) => {
  if (err.type === 'entity.parse.failed') return res.status(400).json({ error: 'Invalid JSON body' })
  console.error('[server]', err)
  res.status(500).json({ error: 'Something went wrong on our side. Please try again.' })
})

app.listen(PORT, () => console.log(`Alpine Ascents API listening on http://localhost:${PORT}`))
